### ISSUE TITLE
Feed events very slow to populate

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#208]
I logged in and all events created earlier this evening have gone and feed is empty, says "You have no events. (Why not create some?) for about 30-40 seconds, then events appear.

**Comment by rickardinho** [comment]
At other times, sometimes the feed shows events, then goes blank or goes back to showing "You have no events.  Why not create some?"

**Comment by heron2014** [comment]
@rickardinho we have made changes to the feed today, this should work now. Please test.

**Comment by rickardinho** [comment]
Retested.  still getting blank feed after iPhone is inactive for a few seconds it locks.  When i unlock it and return straight to Spark app, Feed is blank white page.

**Comment by rickardinho** [comment]
Still getting blank feed when app coming back to the app after it has gone into background.

**Comment by heron2014** [comment]
@rickardinho this should be fixed now. Please test.

**Comment by rickardinho** [comment]
Seems to be fixed, Feed and Calendar are now much faster to load
