### ISSUE TITLE
When editing an event, there is no Where

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#244]
I think in the edit details "What" is shown twice .  There is no "Where".  If i go to edit them, you can see both say "What would you like to do?" - see screenshot.

**Comment by rickardinho** [comment]
Also scrolling not fixed on Edit Event - keyboard still hides bottom inputs.

**Comment by rickardinho** [comment]
and when I click update on Edit event, nothing happens... it should redirect to the previous event details screen.

**Comment by rickardinho** [comment]
![img_5437](https://cloud.githubusercontent.com/assets/17908724/23530768/14460e8c-ff9b-11e6-9d31-d5385760ea6c.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
Scrolling issue still not fixed.  Where is hidden and cannot be edited.

![img_5524](https://cloud.githubusercontent.com/assets/17908724/23613011/892f2332-0275-11e7-9d47-dc69ec4f988c.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
fixed
